// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace QuickJump2022
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string QuickJump2022String = "a9dbbd24-a865-4aba-a916-b5cf41993d73";
        public static Guid QuickJump2022 = new Guid(QuickJump2022String);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MainCmdGroup = 0x0001;
        public const int ShowMethodSearchForm = 0x0100;
        public const int ShowFileSearchForm = 0x0200;
        public const int ShowAllSearchForm = 0x0300;
        public const int ShowMonikerTestDialog = 0x0400;
        public const int ShowAllSearchFormDualWindow = 0x0500;
        public const int ShowSearchToolWindow = 0x0600;
    }
}
